### ISSUE TITLE
Open multiple files at once

### ISSUE THREAD

**Issue by NathanFallet** [GroupeMINASTE/OCaml-iOS#7]
**Is your feature request related to a problem? Please describe.**
Only one file can be edited at once

**Describe the solution you'd like**
Add tabs or something to allow to open multiple files at once

**Describe alternatives you've considered**

**Additional context**

**Comment by Naereen** [comment]
Feel free to see how it works in <https://BetterOCaml.ml/>, and browse its source <https://github.com/jbdo99/BetterOCaml/>
Pinging @jbdo99 just for to inform him.
